# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"himmelblau": "700_optimization.himmelblau.ipynb",
         "grad_himmelblau": "700_optimization.himmelblau.ipynb",
         "hess_himmelblau": "700_optimization.himmelblau.ipynb",
         "line_search": "710_optimization.bfgs.ipynb",
         "bfgs": "710_optimization.bfgs.ipynb",
         "naive_grad": "710_optimization.grad.ipynb",
         "sample": "800_sampling.box_muller.ipynb"}

modules = ["optimization/himmelblau.py",
           "optimization/bfgs.py",
           "optimization/grad.py",
           "sampling/box_muller.py"]

doc_url = "https://blackcherry88.github.io/ml/"

git_url = "https://github.com/blackcherry88/ml/tree/master/"

def custom_doc_links(name): return None
