# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"f": "700_ml.optimization.himmelblau.ipynb",
         "grad_f": "700_ml.optimization.himmelblau.ipynb",
         "hess_f": "700_ml.optimization.himmelblau.ipynb"}

modules = ["ml/optimization/himmelblau.py"]

doc_url = "https://blackcherry88.github.io/ml/"

git_url = "https://github.com/blackcherry88/ml/tree/master/"

def custom_doc_links(name): return None
