# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/700_optimization.himmelblau.ipynb.

# %% auto 0
__all__ = ['himmelblau', 'grad_himmelblau', 'hess_himmelblau']

# %% ../../nbs/700_optimization.himmelblau.ipynb 3
import numpy as np

# Himmelblau function - a common example used for testing optimization algorithms
def himmelblau(x,y):
    return (x*x+y-11)**2+(x+y*y-7)**2

# Gradient of the Himmelblau function
def grad_himmelblau(x,y):
    return np.array([4*x*(x*x+y-11)+2*(x+y*y-7),2*(x*x+y-11)+4*y*(x+y*y-7)])

# Hessian of the Himmelblau function
def hess_himmelblau(x,y):
    return np.array([[4*(x*x+y-11)+8*x*x+2,4*x+4*y],[4*x+4*y,2+4*(x+y*y-7)+8*y*y]])
