# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/800_sampling.box_muller.ipynb.

# %% auto 0
__all__ = ['sample']

# %% ../../nbs/800_sampling.box_muller.ipynb 4
def sample(size=1000):
    U1 = np.random.uniform(size = size)
    U2 = np.random.uniform(size = size)
    R = np.sqrt(-2 * np.log(U1))
    theta = 2 * np.pi * U2
    X = R * np.cos(theta)
    # Y = R * np.sin(theta)
    return X
